version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'jnoble'
      PGDATA: /tmp
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5544:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
  redis:
    image: 'docker.io/bitnami/redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
volumes:
  redis_data:
    driver: local
